name: Publish Package to npmjs
on:
  workflow_dispatch:
  push:
    branches:
    - "test-action"
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --dry-run --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
