name: Publish Package to npmjs
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'test-action'
  pull_request:
    branches:
      - '**'
  release:
    types: [published]
jobs:
  build_test:
    name: Build and Test config
    uses: ./.github/workflows/test.yml

  publish:
    needs: [build_test]
    uses: iconsauce/.github/workflows/publish-npm
