name: Publish Iconsauce Config
on:
  workflow_dispatch:
jobs:
  build_test:
    name: Build and Test config
    uses: ./.github/workflows/test.yml
  publish:
    needs: [build_test]
    name: Publish npm
    uses: iconsauce/.github/.github/workflows/publish-npm.yml@main
